export const LOGIN_URL: string = 'r=api/account-retailer/login'
export const MERCHANT_LOGIN_URL: string = 'r=api/account-retailer/login-via-merchant'
export const ACCOUNT_SETTING: string = 'r=api/account-retailer/update-setting'
export const EDIT_PROFILE: string = 'r=api/account-retailer/edit-profile'
export const UPDATE_TIME_SETUP: string = 'r=api/account-retailer/edit-profile'
export const CREATE_TAXES: string = 'r=api/products-taxes/create'
export const EDIT_TAXES: string = 'r=api/products-taxes/edit'
export const PRODUCT_LIST: string = 'r=api/products/listing'
export const CHANGE_PRODUCT_STATUS: string = 'r=api/products/change'
export const CHANGE_SUBCATEGORY_STATUS: string = 'r=api/products/edit-subcategory-stop'
export const CHANGE_VENDOR_STATUS: string = 'r=api/account-retailer/update-vendor-status'
export const DELETE_PRODUCT_TAX: string = 'r=api/products-taxes/delete'
export const DELETE_SUBCATEGORY: string = 'r=api/products/delete-subcategory'
export const PRODUCT_TAX_LIST: string = 'r=api/products-taxes/listing'
export const ADD_PRODUCT_TAX_LIST: string = 'r=api/products-taxes/create'
export const DELETE_PRODUCT_TAX_LIST: string = 'r=api/products-taxes/delete'
export const EDIT_PRODUCT_TAX_LIST: string = 'r=api/products-taxes/edit'
export const CREATE_PRODUCT: string = 'r=api/products/create'
export const UPLOAD_PRODUCT_IMAGE: string = 'r=api/products/add-images'
export const PRODUCT_CATEGORY: string = 'r=api/products/categories'
export const ADD_PRODUCT_SUBCATEGORY: string = 'r=api/products/add-subcategory'
export const EDIT_PRODUCT_SUBCATEGORY: string =
  'r=api/products/edit-subcategory'
export const PRODUCT_SUBCATEGORY: string = 'r=api/category/vendor-subcategories'
export const PRODUCT_ORDER_LIST: string = 'r=api/products/orders'
export const PRODUCT_DETAIL_ORDER: string = 'r=api/products/order-detail'
export const PRODUCT_CONFIRM_ORDER: string = 'r=api/products/confirm-order'
export const PRODUCT_READY_ORDER: string = 'r=api/products/ready-order'
export const PRODUCT_CANCEL_ORDER: string = 'r=api/products/cancel-order'
export const GET_COUPONS: string = 'r=api/account-retailer/coupons'
export const ADD_COUPON: string = 'r=api/account-retailer/add-coupons'
export const EDIT_COUPON: string = 'r=api/account-retailer/update-coupons'
export const DIRECT_OFFER_DETAIL: string =
  'r=api/account-retailer/direct-offer-details'
export const UPDATE_DIRECT_OFFER_DETAIL: string =
  'r=api/account-retailer/update-offers'
export const ADD_ADDONS: string = 'r=api/products/add-addon'
export const ADD_PARAMETERS: string = 'r=api/products/add-parameter'
export const PRODUCT_DETAIL: string = 'r=api/products/details'
export const UPDATE_PRODUCT: string = 'r=api/products/update'
export const DELETE_PRODUCT: string = 'r=api/products/delete'
export const VENDOR_STATUS: string = 'r=api/account-retailer/vendor-status'
export const SETTING_API: string = 'r=api/account-retailer/settings'
export const IS_AUTHORIZED_API: string = 'r=api/products/validate-token'
export const DASHBOARD_API: string = 'r=api/products/dashboard-data'
export const REVIEWS_API: string = 'r=api/products/reviews'
